#springProperties
spring:
#DataSourceProperties
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
  mail:
    host: smtp.sina.com
    port: 465
    username: xiaoyuer20190319@sina.com
    password: d927b6534369407d
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
#Mybatis properties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.product.xiaoyuer.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#LoggerProperties
logger:
  level:
    org:
      product:
        community: error


#page
page:
  current: 1
  limit: 10
#xiaoyuer
xiaoyuer:
  path:
    domian: localhost:8080/
#serverProperties
server:
  servlet:
    context-path: /xiaoyuer